version: 1.0.0-alpha-{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    dotnet restore

    dotnet pack src/Filehook.Core

    dotnet pack src/Filehook.Proccessors.Image.ImageSharpProccessor

    dotnet pack src/Filehook.Storages.FileSystem
test_script:
- ps: dir test | % { dotnet test $_.FullName }

deploy:
  provider: NuGet
  server: https://www.myget.org/F/filehook/api/v3/index.json
  api_key:
    secure: uUSg50F5ec1bMyNNMvGbFfh6uZa7ItsP4Ug5TVeQPvmpYbFcov2Z1uXy7doyyd+w
  skip_symbols: false
  symbol_server: https://www.myget.org/F/filehook/symbols/api/v2/package
  artifact: /.*\.nupkg/