version: 1.0.0-alpha-{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    dotnet restore

    dotnet pack src/Filehook.Core -o .\artifacts

    dotnet pack src/Filehook.Proccessors.Image.ImageSharpProccessor -o .\artifacts

    dotnet pack src/Filehook.Storages.FileSystem -o .\artifacts

test_script:
- ps: dir test | % { dotnet test $_.FullName }

artifacts:
- path: .\artifacts\**\*.nupkg
  name: NuGet

deploy:
  provider: NuGet
  server: https://www.myget.org/F/filehook/api/v2/package
  api_key:
    secure: uUSg50F5ec1bMyNNMvGbFfh6uZa7ItsP4Ug5TVeQPvmpYbFcov2Z1uXy7doyyd+w
  skip_symbols: false
  symbol_server: https://www.myget.org/F/filehook/symbols/api/v2/package
  artifact: /.*\.nupkg/