image: Visual Studio 2017
version: 1.0.0-alpha-{build}
pull_requests:
  do_not_increment_build_number: true
build_script:
- ps: >-
    dotnet restore

    dotnet pack -c Release --include-symbols -o ./artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.Abstractions -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.Core -o ../../artifacts -c Release --include-symbols --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.Proccessors.Image.ImageSharpProccessor -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.AspNetCore.Http -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.DataAnnotations -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.Proccessors.Image.Abstractions -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

    # dotnet pack src/Filehook.Storages.FileSystem -c Release --include-symbols -o ../../artifacts --version-suffix $env:APPVEYOR_BUILD_NUMBER

test_script:
- ps: dir test | % { dotnet test $_.FullName }

artifacts:
- path: ./src/**/artifacts/*.nupkg
  name: NuGet

deploy:
  - provider: NuGet
    name: MyGet Alpha Chanel
    on:
      branch: dev
    server: https://www.myget.org/F/filehook/api/v2/package
    api_key:
      secure: uUSg50F5ec1bMyNNMvGbFfh6uZa7ItsP4Ug5TVeQPvmpYbFcov2Z1uXy7doyyd+w
    skip_symbols: false
    symbol_server: https://www.myget.org/F/filehook/symbols/api/v2/package
    artifact: /.*\.nupkg/